name: Analysis CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

env:
  DART_SDK_VERSION: "3.3"

permissions:
  contents: read

jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Cache dependencies
        uses: actions/cache@2cdf405574d6ef1f33a1d12acccd3ae82f47b3f2 # v4.1.0
        id: cache
        with:
          path: ~/.pub-cache/hosted
          key: ${{ runner.os }}-pubspec-${{ env.DART_SDK_VERSION }}-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pubspec-${{ env.DART_SDK_VERSION }}-
            ${{ runner.os }}-pubspec-
            ${{ runner.os }}-

      - name: Set up Dart
        uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # v1.7.1
        with:
          sdk: ${{ env.DART_SDK_VERSION }}

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: |
          dart pub global activate coverage
          dart test test/main.dart --coverage=coverage
          dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib

      - name: Coveralls upload
        uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949 # v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
